Repository adobecom/mas, pull requests merged in 2024-07, with the labels that each got.

#7 [MWPW-147172] Support for callout texts in merch cards
  web-components/src/global.css.js
  web-components/src/merch-card.js
  web-components/test/img/info-icon.svg
  web-components/test/merch-card.mini-compare.test.html
  web-components/test/merch-card.test.html
Labels: enhancement, VALIDATED IN MILO

#21 Revert "Revert "MWPW-141119: Change default pricing for Africa site to fix broken prices/promos""
  commerce/src/settings.js
  commerce/test/settings.test.js
Labels: bug, VALIDATED IN MILO

#38 MWPW-154026: Long CTAs fall in the second line in merch card footer
  libs/commerce.js
  libs/mas.js
  libs/merch-card-all.js
  libs/merch-card.js
  web-components/src/merch-card.css.js
  web-components/test/merch-card.test.html
Labels: VALIDATED IN MILO

#15 Mwpw-147034: Custom border color + badge/border color decoupling [Mer…
  web-components/src/merch-card.js
  web-components/test/merch-card.test.html
  web-components/test/merch-card.test.html.js
Labels: enhancement, VALIDATED IN MILO

#43 https://jira.corp.adobe.com/browse/MWPW-148229 -Milo Catalog Batch00d - Left Rail filter hover Text
  libs/merch-sidenav.js
  web-components/src/sidenav/merch-sidenav-checkbox-group.js
  web-components/src/sidenav/merch-sidenav-list.js
  web-components/src/sidenav/merch-sidenav.js
  web-components/test/sidenav/catalog-sidenav.test.html
Labels: bug, good first issue, VALIDATED IN MILO

#45 [MWPW-154335] [callout] Spacing issue encountered when the call-out section is added
  libs/merch-card-all.js
  libs/merch-card.js
  libs/merch-sidenav.js
  libs/plans-modal.js
  web-components/src/global.css.js
  web-components/src/merch-card.css.js
  web-components/src/merch-card.js
  web-components/test/merch-card.mini-compare.test.html
  web-components/test/merch-card.mini-compare.test.html.js
  web-components/test/merch-card.test.html
Labels: VALIDATED IN MILO
