Repository adobecom/mas, pull requests merged in 2024-12, with the labels that each got.

#102 MWPW-162740: Fix unresponsive CTA RTE field
  studio/src/rte/ost.js
  studio/src/rte/rte-field.js
  studio/test/rte/rte-field.test.html
Labels: bug, verified

#106 MWPW-162805 allow stage tests
  k6-scripts/wcs-fetches.js
Labels: trivial

#107 Spectrum CSS support for cards.
  package-lock.json
  package.json
  studio.html
  studio/build.mjs
  studio/libs/spectrum.css
  studio/libs/spectrum.js
  studio/src/spectrum.css.js
  studio/test/aem/content-navigation.test.html.js
  studio/test/rte/rte-field.test.html
Labels: verified

#108 MWPW-158966: add healthcheck action
  .gitignore
  io-actions/README.md
  io-actions/app.config.yaml
  io-actions/jest.config.js
  io-actions/jest.setup.js
  io-actions/package-lock.json
  io-actions/package.json
  io-actions/src/health-check/README.md
  io-actions/src/health-check/index.js
  io-actions/test/health-check.test.js
Labels: verified

#104 MWPW-163041: add register-now & fix extra spaces
  studio/src/constants.js
  studio/src/rte/rte-link-editor.js
Labels: verified

#100 MWPW-162614: Normalize UX for field updates
  package-lock.json
  package.json
  studio/src/aem/aem-fragments.js
  studio/src/aem/aem.js
  studio/src/aem/fragment.js
  studio/src/aem/render-view-item.js
  studio/src/aem/render-view.js
  studio/src/editor-panel.js
  studio/src/editors/merch-card-editor.js
  studio/src/editors/variant-picker.js
  studio/src/events.js
  studio/src/fields/mnemonic-field.js
  studio/src/fields/multifield.js
  studio/src/rte/rte-field.js
  studio/src/studio.js
  studio/src/utils/debounce.js
  studio/style.css
  studio/test/editor-panel.test.html
  studio/test/fields/multifield.test.js
  studio/test/mocks/sites/cf/fragments/cc-all-apps.json
  studio/test/utils.js
Labels: verified
