Repository adobecom/mas, pull requests merged in 2025-04, with the labels that each got.

#221 MWPW-170813 pipeline enhancements
  io/www/src/fragment/common.js
  io/www/src/fragment/pipeline.js
  io/www/test/fragment/pipeline.test.js
Labels: www/io

#202 MWPW-168589: Placeholders in M@S
  nala/libs/auth.setup.cjs
  nala/studio/studio.test.js
  studio/libs/swc.js
  studio/src/aem/aem.js
  studio/src/aem/mas-filter-panel.js
  studio/src/constants.js
  studio/src/editor-panel.js
  studio/src/events.js
  studio/src/img/promos-icon.js
  studio/src/mas-content.js
  studio/src/mas-placeholders.css.js
  studio/src/mas-placeholders.js
  studio/src/mas-repository.js
  studio/src/mas-side-nav.js
  studio/src/mas-splash-screen.js
  studio/src/mas-toolbar.js
  studio/src/mas-top-nav.js
  studio/src/router.js
  studio/src/rte/rte-field.js
  studio/src/store.js
  studio/src/studio.js
  studio/src/swc.js
  studio/src/utils.js
  studio/style.css
  studio/test/aem/mas-content.test.html
  studio/test/aem/mas-placeholders.test.html
  studio/test/aem/mas-placeholders.test.html.js
  studio/test/aem/mas-repository.test.js
  studio/test/store/hash-linking.test.js
  studio/test/store/router.test.js
Labels: enhancement, verified

#195 MWPW-164491 [Plans] Updates to Individuals wide key apps merch-card
  studio.html
  studio/merch-card.css
  studio/src/editors/merch-card-editor.js
  studio/src/fields/included-field.js
  studio/style.css
Labels: verified

#219 MWPW-165461: Added content-type to use url
  studio/src/editor-panel.js
Labels: verified

#216 MWPW-169300 [Plans] Custom colors on Plans card badges
  studio/src/editors/merch-card-editor.js
  studio/style.css
Labels: do not merge, verified

#222 MWPW-170897: Unordered list action for rte-field
  .vscode/settings.json
  studio/libs/prosemirror.js
  studio/libs/swc.js
  studio/src/editors/merch-card-editor.js
  studio/src/router.js
  studio/src/rte/prosemirror.js
  studio/src/rte/rte-field.js
  studio/src/swc.js
Labels: verified

#220 MWPW-169084: Part 2 & 3: Update the USE text and same text to be card title on editor.
  nala/studio/editor.page.js
  nala/studio/studio.test.js
  studio/src/aem/fragment.js
  studio/src/editor-panel.js
Labels: verified

#229 MWPW-165481: support modals/entitlements/upgrade in M@S CTA
  .github/pull_request_template.md
  studio/ost/index.css
  studio/ost/index.js
  studio/src/rte/ost.js
  studio/src/rte/rte-field.js
  studio/test/rte/ost.test.js
Labels: verified

#228 MWPW 170033: secure transaction label
  io/www/src/fragment/pipeline.js
  io/www/src/fragment/settings.js
  io/www/test/fragment/pipeline.test.js
  io/www/test/fragment/settings.test.js
  studio/src/editors/merch-card-editor.js
  studio/src/fields/secure-text-field.js
Labels: verified

#240 MWPW-167198: update commerce locale on locale filter change
  studio.html
  studio/src/rte/ost.js
  studio/src/studio.js
Labels: verified
