Repository adobecom/mas, pull requests merged in 2025-03, with the labels that each got.

#182 fix to 412 errors
  studio/src/aem/aem.js
Labels: verified

#183 MWPW-169073 log main steps
  io-actions/src/fragment/collection.js
  io-actions/src/fragment/common.js
  io-actions/src/fragment/fetch.js
  io-actions/src/fragment/pipeline.js
  io-actions/src/fragment/replace.js
  io-actions/src/fragment/translate.js
  io-actions/test/fragment/collection.test.js
  io-actions/test/fragment/replace.test.js
  io-actions/test/fragment/translate.test.js
Labels: trivial

#188 MWPW-169011: CTA attribute remove fix
  studio/src/rte/rte-field.js
Labels: verified

#161 MWPW-167305 Callout Info Icon
  studio/src/editors/merch-card-editor.js
  studio/src/rte/rte-field.js
  studio/src/rte/rte-icon-editor.js
  studio/src/studio.js
  studio/src/swc.js
Labels: VALIDATED IN MILO, verified

#193 MWPW-169619: fix stale IMS session issue
  studio.html
Labels: verified

#198 [releng][trivial] ignore local studio io files
  .gitignore
Labels: trivial

#179 MWPW-168870: CTA class fix
  nala/studio/ahome/try-buy-widget/tests/try_buy_widget_discard.test.js
  nala/studio/ahome/try-buy-widget/tests/try_buy_widget_edit.test.js
  nala/studio/ahome/try-buy-widget/tests/try_buy_widget_save.test.js
  nala/studio/ccd/slice/tests/slice_discard.test.js
  nala/studio/ccd/slice/tests/slice_edit.test.js
  nala/studio/ccd/slice/tests/slice_save.test.js
  nala/studio/ccd/suggested/tests/suggested_discard.test.js
  nala/studio/ccd/suggested/tests/suggested_edit.test.js
  nala/studio/ccd/suggested/tests/suggested_save.test.js
  studio/src/rte/rte-field.js
  studio/test/rte/rte-field.test.html
Labels: verified

#199 MWPW-169885: delay mas init for IMS to be ready
  studio.html
Labels: verified

#203 MWPW-170036 fixing adobe-home surface cards
  io/studio/src/fragment/paths.js
  io/www/src/fragment/paths.js
  io/www/src/fragment/pipeline.js
  io/www/src/fragment/translate.js
  io/www/test/fragment/paths.test.js
  io/www/test/fragment/pipeline.test.js
  io/www/test/fragment/translate.test.js
Labels: trivial

#204 MWPW-170089 logging output body id
  io/www/src/fragment/pipeline.js
Labels: trivial

#200 MWPW-164951 highlight edited card
  studio/src/constants.js
  studio/src/editor-panel.js
  studio/src/editors/merch-card-editor.js
  studio/style.css
Labels: verified

#205 MWPW-170089 fixing response discrepancies
  io/studio/src/fragment/pipeline.js
  io/www/src/fragment/fetch.js
  io/www/src/fragment/pipeline.js
  io/www/test/fragment/mocks/MockState.js
  io/www/test/fragment/pipeline.test.js
  scripts/k6/fragment-fetches.js
  scripts/k6/fragment-files/fragments.csv
Labels: trivial

#212 MWPW-169084: fragment > query for USE link.
  studio/src/editor-panel.js
Labels: do not merge, verified
