Repository adobecom/mas, pull requests merged in 2025-02, with the labels that each got.

#123 MWPW-161354: filter unused fields in the editor
  nala/studio/studio.page.js
  nala/studio/studio.test.js
  studio/libs/swc.js
  studio/proxy-server.mjs
  studio/src/constants.js
  studio/src/editor-panel.js
  studio/src/editors/merch-card-editor.js
  studio/src/mas-fragment.js
  studio/src/mas-repository.js
  studio/src/reactivity/fragment-store.js
  studio/src/reactivity/reactive-controller.js
  studio/src/reactivity/reactive-store.js
  studio/src/store.js
  studio/src/swc.js
  studio/style.css
  studio/test/editor-panel.test.html
  studio/test/mocks/folders/default.json
Labels: verified

#138 Fix drag start handling to correctly reference the active element in …
  .github/pull_request_template.md
  studio/src/fields/multifield.js
Labels: verified

#130 MWPW-164253 non VPN OST
  .github/workflows/ost-products.yaml
  eslint.config.mjs
  io-actions/README.md
  io-actions/app.config.yaml
  io-actions/package-lock.json
  io-actions/package.json
  io-actions/src/health-check/README.md
  io-actions/src/ost-products/README.md
  io-actions/src/ost-products/read.js
  io-actions/src/ost-products/write.js
  studio/ost/index.css
  studio/ost/index.js
Labels: verified

#152 MWPW-167034: removed scroll for surface switch
  studio/src/mas-side-nav.js
Labels: verified

#139 MWPW-166073: adding z-index to editor
  studio/ost/index.js
  studio/style.css
Labels: verified

#143 MWPW-165482 milo autoblock feature
  studio/src/editor-panel.js
  studio/src/editors/variant-picker.js
  studio/test/editor-panel.test.html
Labels: verified

#156 MWPW-164492 Plans Card Authoring v0.1
  .gitignore
  studio/src/editor-panel.js
  studio/src/editors/merch-card-editor.js
  studio/src/editors/variant-picker.js
  studio/src/swc.js
Labels: verified

#149 MWPW-166929: Added logic to close popover if folder picker loses focus
  studio/src/mas-folder-picker.js
Labels: verified

#151 MWPW-166928: update to check for fragment id before removing from results
  studio/src/mas-repository.js
Labels: verified

#163 MWPW-158500: Universal promo terms link
  studio/libs/swc.js
  studio/src/editors/merch-card-editor.js
  studio/src/rte/rte-field.js
  studio/src/swc.js
Labels: VALIDATED IN MILO, verified

#164 MWPW-167647: Automatic folder selection for single fragment search
  nala/studio/studio.page.js
  nala/studio/studio.test.js
  studio/src/mas-repository.js
Labels: verified

#172 MWPW-168180 remove path related infos from editor
  studio/src/editor-panel.js
Labels: verified, trivial

#166 MWPW-166677: Migrate Milo MAS to HLX5
  .gitignore
  README.md
  io-actions/test/fragment/mocks/collection.json
  nala/studio/ccd/suggested/specs/suggested_discard.spec.js
  nala/studio/ccd/suggested/specs/suggested_edit.spec.js
  nala/utils/pr.run.sh
  ost-audit/audit.mjs
  studio/src/maslib.js
Labels: verified

#159 MWPW-164093: Adobe Home 'Buy Try Widget' merch card
  .gitignore
  nala/studio/ccd/slice/tests/slice_discard.test.js
  nala/studio/ccd/slice/tests/slice_edit.test.js
  nala/studio/ccd/slice/tests/slice_save.test.js
  studio/src/editors/merch-card-editor.js
  studio/src/editors/variant-picker.js
  studio/src/rte/rte-field.js
  studio/src/rte/rte-link-editor.js
  studio/src/utils/spectrum-colors.js
Labels: VALIDATED IN MILO, verified

#155 MWPW-165449: Tag picker in the filter-panel
  .vscode/settings.json
  package-lock.json
  package.json
  studio/libs/swc.js
  studio/src/aem/aem-tag-picker-field.js
  studio/src/aem/aem.js
  studio/src/aem/mas-filter-panel.js
  studio/src/constants.js
  studio/src/editor-panel.js
  studio/src/filters/locale-picker.js
  studio/src/mas-repository.js
  studio/src/reactivity/fragment-store.js
  studio/src/reactivity/reactive-store.js
  studio/src/store.js
  studio/src/studio.js
  studio/src/swc.js
  studio/test/aem/aem-tag-picker-field.test.html
  studio/test/aem/aem.test.js
  studio/test/aem/mas-filter-panel.test.html
  studio/test/mocks/tags.json
  studio/test/store/hash-linking.test.js
Labels: verified
